name: Update Staging
on:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  image: ${{ github.event.repository.name }}:$GITHUB_SHA

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:    
      - name: Updating System
        run: sudo apt-get install -f
      - uses: actions/checkout@v2
      - name: Adding Environment Variables
        run: echo "${{secrets.ENVIRONMENT}}" > .env.local
        shell: bash
      - name: Creating image
        run: docker build -t ${{ env.image }} .
      - name: Sending image to server
        uses: ./.github/actions/send-build
        with:
          image: ${{ env.image }}
          destination: ${{ secrets.STAGING_DESTINATION }}
          key: ${{ secrets.STAGING_KEY }}
      - name: Starting Image
        uses: ./.github/actions/start-image
        with:
          service: frontend
          image: ${{ env.image }}
          destination: ${{ secrets.STAGING_DESTINATION }}
          key: ${{ secrets.STAGING_KEY }}